# Generated by Django 3.2 on 2023-07-15 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('sale_area', models.CharField(max_length=130)),
                ('territory', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=50, null=True)),
                ('overview', models.CharField(max_length=400)),
                ('website', models.CharField(blank=True, max_length=70, null=True)),
                ('industry_type', models.CharField(max_length=60)),
                ('specialities', models.CharField(max_length=60)),
                ('company_size', models.IntegerField()),
                ('headquaters', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_avatar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
