# Generated by Django 3.2 on 2023-07-18 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='state',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='zip',
        ),
    ]
