# Generated by Django 3.2 on 2023-07-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230718_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='expire_membership_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='membership_type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='remaing_request',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
