# Generated by Django 3.2 on 2023-07-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230728_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='password',
            new_name='gmail_password',
        ),
    ]
