# Generated by Django 3.2 on 2023-07-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_password_avatar_gmail_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='remaing_request',
        ),
        migrations.AddField(
            model_name='avatar',
            name='remaing_email_request',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='remaing_financial_request',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='remaing_grant_request',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
