# Generated by Django 3.2 on 2023-08-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
